---
title: North - Game
author: Matthias Koch & Lars Mäder
email: mail@larsmaeder.ch
description: "Game Konzept von Matthias Koch und Lars Mäder, Interaction Design Studierende.\nFür
  das Modul «Game Design» unterrichtet and der Schule für Gestaltung Zürich (SFGZ) "
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
